// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzNFFD4WI5hTEjIqV_DBdd8an1KDAbpU',
    appId: '1:737208879758:web:da959d31e37c9b48c957df',
    messagingSenderId: '737208879758',
    projectId: 'mobile-app-project-43d39',
    authDomain: 'mobile-app-project-43d39.firebaseapp.com',
    storageBucket: 'mobile-app-project-43d39.firebasestorage.app',
    measurementId: 'G-BKS2J2MT81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHzNFFD4WI5hTEjIqV_DBdd8an1KDAbpU',
    appId: '1:737208879758:android:your-android-app-id',
    messagingSenderId: '737208879758',
    projectId: 'mobile-app-project-43d39',
    storageBucket: 'mobile-app-project-43d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHzNFFD4WI5hTEjIqV_DBdd8an1KDAbpU',
    appId: '1:737208879758:ios:your-ios-app-id',
    messagingSenderId: '737208879758',
    projectId: 'mobile-app-project-43d39',
    storageBucket: 'mobile-app-project-43d39.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHzNFFD4WI5hTEjIqV_DBdd8an1KDAbpU',
    appId: '1:737208879758:ios:your-ios-app-id',
    messagingSenderId: '737208879758',
    projectId: 'mobile-app-project-43d39',
    storageBucket: 'mobile-app-project-43d39.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzNFFD4WI5hTEjIqV_DBdd8an1KDAbpU',
    appId: '1:737208879758:web:da959d31e37c9b48c957df',
    messagingSenderId: '737208879758',
    projectId: 'mobile-app-project-43d39',
    authDomain: 'mobile-app-project-43d39.firebaseapp.com',
    storageBucket: 'mobile-app-project-43d39.firebasestorage.app',
  );
}
